#python assemble_best.py synthesis_files/neighbors_trees-mult_16_preoptimized_falcon_16_blocksize_4_scan
#python assemble_best.py synthesis_files/neighbors_trees-qft_100_preoptimized_falcon_113_blocksize_4_scan
#python assemble_best.py synthesis_files/neighbors_trees-add_101_preoptimized_falcon_113_blocksize_4_scan

#python assemble_best.py synthesis_files/neighbors_embedded-add_5_preoptimized_mesh_9_blocksize_4_scan
#python assemble_best.py synthesis_files/neighbors_embedded-add_17_preoptimized_mesh_25_blocksize_4_scan
#python assemble_best.py synthesis_files/neighbors_embedded-add_41_preoptimized_mesh_49_blocksize_4_scan
#python assemble_best.py synthesis_files/neighbors_embedded-add_81_preoptimized_mesh_81_blocksize_4_scan
#python assemble_best.py synthesis_files/neighbors_trees-add_5_preoptimized_mesh_9_blocksize_4_scan
#python assemble_best.py synthesis_files/neighbors_trees-add_17_preoptimized_mesh_25_blocksize_4_scan
#python assemble_best.py synthesis_files/neighbors_trees-add_41_preoptimized_mesh_49_blocksize_4_scan
python assemble_best.py synthesis_files/neighbors_trees-add_81_preoptimized_mesh_81_blocksize_4_scan

#python assemble_best.py synthesis_files/neighbors_biased-mult_16_preoptimized_mesh_16_blocksize_4_scan
#python assemble_best.py synthesis_files/neighbors_biased-qft_64_preoptimized_mesh_64_blocksize_4_scan
#python assemble_best.py synthesis_files/neighbors_biased-add_65_preoptimized_mesh_81_blocksize_4_scan
#python assemble_best.py synthesis_files/neighbors_biased-hubbard_18_preoptimized_mesh_25_blocksize_4_scan
#python assemble_best.py synthesis_files/neighbors_biased-tfim_40_preoptimized_mesh_49_blocksize_4_scan
#python assemble_best.py synthesis_files/neighbors_biased-shor_26_preoptimized_mesh_36_blocksize_4_scan

#python assemble_best.py synthesis_files/neighbors_trees-qft_100_preoptimized_mesh_100_blocksize_4_scan
#python assemble_best.py synthesis_files/neighbors_trees-add_101_preoptimized_mesh_121_blocksize_4_scan
#python assemble_best.py synthesis_files/neighbors_embedded-qft_100_preoptimized_mesh_100_blocksize_4_scan
#python assemble_best.py synthesis_files/neighbors_embedded-add_101_preoptimized_mesh_121_blocksize_4_scan
#python assemble_best.py synthesis_files/neighbors_best-qft_100_preoptimized_mesh_100_blocksize_4_scan
#python assemble_best.py synthesis_files/neighbors_best-add_101_preoptimized_mesh_121_blocksize_4_scan
#python assemble_best.py synthesis_files/neighbors_biased-qft_100_preoptimized_mesh_100_blocksize_4_scan
#python assemble_best.py synthesis_files/neighbors_biased-add_101_preoptimized_mesh_121_blocksize_4_scan

#python assemble_best.py synthesis_files/mult_16_preoptimized_linear_16_blocksize_4_scan
#python assemble_best.py synthesis_files/mult_32_preoptimized_linear_32_blocksize_4_scan
#python assemble_best.py synthesis_files/qft_64_preoptimized_linear_64_blocksize_4_scan
#python assemble_best.py synthesis_files/qft_100_preoptimized_linear_100_blocksize_4_scan
#python assemble_best.py synthesis_files/add_65_preoptimized_linear_65_blocksize_4_scan
#python assemble_best.py synthesis_files/add_101_preoptimized_linear_101_blocksize_4_scan
#python assemble_best.py synthesis_files/tfim_40_preoptimized_linear_40_blocksize_4_scan
#python assemble_best.py synthesis_files/tfim_100_preoptimized_linear_100_blocksize_4_scan
#python assemble_best.py synthesis_files/hubbard_18_preoptimized_linear_18_blocksize_4_scan
#python assemble_best.py synthesis_files/shor_26_preoptimized_linear_26_blocksize_4_scan

#python assemble_best.py synthesis_files/trees-mult_16_preoptimized_falcon_16_blocksize_4_scan
#python assemble_best.py synthesis_files/trees-mult_32_preoptimized_falcon_65_blocksize_4_scan
#python assemble_best.py synthesis_files/trees-qft_64_preoptimized_falcon_65_blocksize_4_scan
#python assemble_best.py synthesis_files/trees-qft_100_preoptimized_falcon_113_blocksize_4_scan
#python assemble_best.py synthesis_files/trees-add_65_preoptimized_falcon_65_blocksize_4_scan
#python assemble_best.py synthesis_files/trees-add_101_preoptimized_falcon_113_blocksize_4_scan
#python assemble_best.py synthesis_files/trees-hubbard_18_preoptimized_falcon_27_blocksize_4_scan
#python assemble_best.py synthesis_files/trees-shor_26_preoptimized_falcon_27_blocksize_4_scan

#python assemble_best.py synthesis_files/embedded-mult_16_preoptimized_falcon_16_blocksize_4_scan
#python assemble_best.py synthesis_files/embedded-mult_32_preoptimized_falcon_65_blocksize_4_scan
#python assemble_best.py synthesis_files/embedded-qft_64_preoptimized_falcon_65_blocksize_4_scan
#python assemble_best.py synthesis_files/embedded-qft_100_preoptimized_falcon_113_blocksize_4_scan
#python assemble_best.py synthesis_files/embedded-add_65_preoptimized_falcon_65_blocksize_4_scan
#python assemble_best.py synthesis_files/embedded-add_101_preoptimized_falcon_113_blocksize_4_scan
#python assemble_best.py synthesis_files/embedded-hubbard_18_preoptimized_falcon_27_blocksize_4_scan
#python assemble_best.py synthesis_files/embedded-shor_26_preoptimized_falcon_27_blocksize_4_scan

#python assemble_best.py synthesis_files/best-mult_16_preoptimized_falcon_16_blocksize_4_scan
#python assemble_best.py synthesis_files/best-mult_32_preoptimized_falcon_65_blocksize_4_scan
#python assemble_best.py synthesis_files/best-qft_64_preoptimized_falcon_65_blocksize_4_scan
#python assemble_best.py synthesis_files/best-qft_100_preoptimized_falcon_113_blocksize_4_scan
#python assemble_best.py synthesis_files/best-add_65_preoptimized_falcon_65_blocksize_4_scan
#python assemble_best.py synthesis_files/best-add_101_preoptimized_falcon_113_blocksize_4_scan
#python assemble_best.py synthesis_files/best-hubbard_18_preoptimized_falcon_27_blocksize_4_scan
#python assemble_best.py synthesis_files/best-shor_26_preoptimized_falcon_27_blocksize_4_scan

#python assemble_best.py synthesis_files/biased-mult_16_preoptimized_falcon_16_blocksize_4_scan
#python assemble_best.py synthesis_files/biased-mult_32_preoptimized_falcon_65_blocksize_4_scan
#python assemble_best.py synthesis_files/biased-qft_64_preoptimized_falcon_65_blocksize_4_scan
#python assemble_best.py synthesis_files/biased-qft_100_preoptimized_falcon_113_blocksize_4_scan
#python assemble_best.py synthesis_files/biased-add_65_preoptimized_falcon_65_blocksize_4_scan
#python assemble_best.py synthesis_files/biased-add_101_preoptimized_falcon_113_blocksize_4_scan
#python assemble_best.py synthesis_files/biased-hubbard_18_preoptimized_falcon_27_blocksize_4_scan
#python assemble_best.py synthesis_files/biased-shor_26_preoptimized_falcon_27_blocksize_4_scan


#python assemble_best.py synthesis_files/neighbors_biased-qft_10_preoptimized_mesh_16_blocksize_4_scan
#python assemble_best.py synthesis_files/neighbors_biased-qft_15_preoptimized_mesh_16_blocksize_4_scan
#python assemble_best.py synthesis_files/neighbors_biased-qft_25_preoptimized_mesh_25_blocksize_4_scan
#python assemble_best.py synthesis_files/neighbors_biased-qft_40_preoptimized_mesh_49_blocksize_4_scan
