
python assemble_conglomerate.py synthesis_files/trees-mult_16_preoptimized_mesh_16_blocksize_4_scan
python assemble_conglomerate.py synthesis_files/trees-qft_64_preoptimized_mesh_64_blocksize_4_scan
python assemble_conglomerate.py synthesis_files/trees-add_65_preoptimized_mesh_81_blocksize_4_scan
python assemble_conglomerate.py synthesis_files/trees-hubbard_18_preoptimized_mesh_25_blocksize_4_scan
python assemble_conglomerate.py synthesis_files/trees-shor_26_preoptimized_mesh_36_blocksize_4_scan

#python assemble_conglomerate.py synthesis_files/embedded-mult_16_preoptimized_mesh_16_blocksize_4_scan
#python assemble_conglomerate.py synthesis_files/embedded-qft_64_preoptimized_mesh_64_blocksize_4_scan
#python assemble_conglomerate.py synthesis_files/embedded-add_65_preoptimized_mesh_81_blocksize_4_scan
#python assemble_conglomerate.py synthesis_files/embedded-hubbard_18_preoptimized_mesh_25_blocksize_4_scan
#python assemble_conglomerate.py synthesis_files/embedded-shor_26_preoptimized_mesh_36_blocksize_4_scan
